#!/bin/bash
#
# Generate the list of read-only PostgreSQL built-in functions used by
# `route_unknown_functions_to_primary`: every pg_catalog function name
# that is IMMUTABLE or STABLE in all of its overloads. A name with any
# VOLATILE overload is left out, and so are the few that are not volatile
# but refuse to run on a standby (NOT_ON_STANDBY below).
#
# Run it against the PostgreSQL version the list should match, e.g.:
#
#   PSQL="psql -h 127.0.0.1 -U postgres" bash scripts/pg_catalog_functions.sh \
#       > pgdog/src/frontend/router/parser/function/pg_catalog.rs
#
set -euo pipefail

PSQL=${PSQL:-psql}

# Stable or immutable, but "cannot execute ... during recovery" on a standby:
# they assign a transaction id or read the WAL position of a primary.
NOT_ON_STANDBY="'txid_current', 'pg_current_xact_id', 'pg_walfile_name', 'pg_walfile_name_offset'"

version=$($PSQL -XAtc "select current_setting('server_version')")
names=$($PSQL -XAtc "
    select proname
    from pg_proc
    where pronamespace = 'pg_catalog'::regnamespace
      and proname not in (${NOT_ON_STANDBY})
    group by proname
    having bool_and(provolatile in ('i', 's'))
    order by proname collate \"C\"")

if echo "$names" | grep -q '[^a-z0-9_]'; then
    echo "unexpected characters in a function name" >&2
    exit 1
fi

count=$(echo "$names" | wc -l)

cat <<RUST
//! Generated by \`scripts/pg_catalog_functions.sh\` from PostgreSQL ${version}. Do not edit.
//!
//! \`pg_catalog\` functions that are \`IMMUTABLE\` or \`STABLE\` in every overload,
//! sorted by byte for binary search. A name with any \`VOLATILE\` overload is left out,
//! and so are ${NOT_ON_STANDBY}: they fail on a standby.

pub(super) static READ_ONLY: [&str; ${count}] = [
RUST
echo "$names" | sed 's/.*/    "&",/'
echo "];"
